import ThemeToggler from '@components/ui/theme-toggler';
import Head from 'next/head';
import React from 'react';

interface Props {
    children: React.ReactNode;
}

const MainLayout: React.FC<Props> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Tipai</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <ThemeToggler></ThemeToggler>
            </header>
            <main className="container">{children}</main>
        </>
    );
};

export default MainLayout;
